# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4b955750650fb7fe4a235ace4e8f73679828a363065016a76cb1b8b77f4ea64a1d758d1b36f22384d708946927a5864a847b79cb0c06ec9f4439fb3765513e

test:
  secret_key_base: 3abf9b7a9d77c13e56e81b281d9e3be92ab13b3892bb37425072f9409e398783b90f8a3ea0c6189f1056c92252d1af106c2097e4b0e6a96af4dc6f7c2dfc0695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
